@startuml

package Model{
    class World
    class Chunk

    abstract Block
    abstract Translucent
    abstract Orientable
    abstract Powerable
    abstract Interactable
    abstract CollideCombinable
    abstract RenderCombinable
    abstract Strikeable
    abstract Destroyable
    abstract StateUpdate
    abstract StandartBlock

    Block <|-- Translucent
    Block <|-- Orientable
    Block <|-- Powerable
    Block <|-- Interactable
    Block <|-- CollideCombine
    Block <|-- RenderCombinable
    Block <|-- Strikeable
    Block <|-- Destroyable
    Block <|-- StateUpdate
    StandartBlock --|> StateUpdate
    StandartBlock --|> Destroyable
    StandartBlock --|> Strikeable
    StandartBlock --|> RenderCombinable
    StandartBlock --|> CollideCombinable

    class Stone
    class Cobblestone
    Stone --|> StandartBlock
    Cobblestone --|> StandartBlock

    abstract Entity
    class EntityMinecart
    class EntityThrowable
    class EntityFX
    class EntityWeatherEffect
    class EntityHanging
    class EntityLivingBase
    class EntityPlayer {
    getPosition()
    }
    class EntityLiving
    class EntityAmbiantCreature
    class EntityFlying
    class EntityCreature
    class EntityMob
    class EntityWaterMob
    class EntityGolem
    class EntityAgeable
    class EntityAnimal
    class EntityTameable

    EntityMinecart --|> Entity
    EntityThrowable --|> Entity
    EntityFX --|> Entity
    EntityWeatherEffect --|> Entity
    EntityHanging --|> Entity
    EntityLivingBase --|> Entity
    EntityPlayer --|> EntityLivingBase
    EntityLiving --|> EntityLivingBase
    EntityAmbiantCreature --|> EntityLiving
    EntityFlying --|> EntityLiving
    EntityCreature --|> EntityLiving
    EntityMob --|> EntityCreature
    EntityWaterMob --|> EntityCreature
    EntityGolem --|> EntityCreature
    EntityAgeable --|> EntityCreature
    EntityAnimal --|> EntityAgeable
    EntityTameable --|> EntityAnimal

    class Position
    class Inventory
    class AbstractPhysics

    EntityPlayer --> Position
    EntityPlayer --> Inventory
    Entity --> AbstractPhysics
    WaterMobPhysics --|> AbstractPhysics
    LandMobPhysics --|> AbstractPhysics
    AerialMobPhysics --|> AbstractPhysics

    World o--> "0..*" Chunk
    Chunk o--> "0..*" Block
}

package Controller{
    class Minecraft{
        runGameLoop()
        runTick()
    }
}

package View{
    class EntityRenderer{
        updateCameraAndRender()
    }
    class WorldRenderer
}

@enduml